os: linux


language: python


matrix:
    include:
        - dist: xenial
          python: 2.7
        - dist: xenial
          python: 3.6
        - dist: trusty
          python: 2.7
        - dist: trusty
          python: 3.6


sudo: required


before_install:
  - sudo apt-get install -y python-dev autoconf libtool make unzip g++ pkg-config cmake python-pip build-essential
  - pip install setuptools


before_script:
  - cd 3rd_party && ./prereq-build.sh && cd ..
  - mkdir pyext/build && cd pyext/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make


script:
  - mkdir ~/result && cp pysamprof.so ~/result/ && cp trace_writer/pysamprof-server ~/result/

