os: linux

dist: xenial

language: python

python:
  - "2.7"
  - "3.6"

sudo: required

before_install:
  - sudo apt-get install -y autoconf libtool make unzip g++ pkg-config cmake

before_script:
  - python --version
  - if [[ $TRAVIS_PYTHON_VERSION = "3.6" ]]; then sudo ln -fs python3.6-config $(which python-config); fi
  - cd 3rd_party && ./prereq-build.sh && cd ..
  - mkdir pyext/build && cd pyext/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

script:
  - mkdir ~/result && cp pysamprof.so ~/result/ && cp trace_writer/pysamprof-server ~/result/

