os: linux

dist: xenial

language: c


matrix:
    include:
        - env: PYTHON="python2.7"
        - env: PYTHON="python3.6"

sudo: required


before_install:
  - sudo apt update
  - sudo apt-get install $PYTHON
  - sudo apt-get install -y python-dev autoconf libtool make unzip g++ pkg-config cmake python-pip
  - pip install setuptools


before_script:
  - python --version
  - cd 3rd_party && ./prereq-build.sh && cd ..
  - mkdir pyext/build && cd pyext/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make


script:
  - mkdir ~/result && cp pysamprof.so ~/result/ && cp trace_writer/pysamprof-server ~/result/

