os: linux

dist: xenial

language: python #this string allows to test 2 versions of python, unlike language: c

python:
  - "2.7"
  - "3.6"

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get update -y
  - sudo apt-get install -y libpython3.6
  - sudo apt-get install -y autoconf libtool make unzip g++ pkg-config cmake

before_script:
  - python --version
  - sudo ln -fs "python$TRAVIS_PYTHON_VERSION-config" "$(which python-config)"
  - cd 3rd_party && ./prereq-build.sh && cd ..
  - mkdir pyext/build && cd pyext/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

script:
  - mkdir ~/result && cp pysamprof.so ~/result/ && cp trace_writer/pysamprof-server ~/result/

